# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-01 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='imgname',
            field=models.CharField(default='', max_length=255),
        ),
    ]
