# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-02 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('br', '0002_icecream_imgname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('favorited', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='br.IceCream')),
                ('favoriter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='br.User')),
            ],
        ),
    ]
